### ISSUE TITLE
ReadEveryTime does not work for Reset or HardDelete

### ISSUE THREAD

**Issue by haseebawan324** [JonPSmith/EfCore.SoftDeleteServices#14]
I am referring to a line in `CascadeWalker` constructor:

`_readEveryTime = readEveryTime && whatDoing == CascadeSoftDelWhatDoing.SoftDelete;`

This piece of code reserves the `ReadEveryTime` option only for the **SoftDelete** action. Meaning Cascade Walker will not read every time for **Reset** or **HardDelete**. Currently, I am using your approach of keeping collections that are not loaded to null.

Can you please suggest a better way to achieve cascade behavior for Reset?

**Comment by JonPSmith** [comment]
Hi @haseebawan324,

The `ReadEveryTime` is there to improve the performance of the EfCore.SoftDeleteServices, but it only works in a **SoftDelete**. That because **Reset** or **HardDelete** must be loaded by this SoftDeleteService because once something is soft deleted then a normal `Include` wouldn't load the soft deleted entries (see [last line of the comment](https://github.com/JonPSmith/EfCore.SoftDeleteServices/blob/master/SoftDeleteServices/Configuration/CascadeSoftDeleteConfiguration.cs#L50L55) on the `ReadEveryTime` property)

So this works as required, but I hadn't provided documentation on this feature. Therefore I added a section about the [`ReadEveryTime` property]( https://github.com/JonPSmith/EfCore.SoftDeleteServices/wiki/Configuring-Soft-Delete#bool-readeverytime-property).
