### ISSUE TITLE
Use service in DbContext

### ISSUE THREAD

**Issue by ksydex** [JonPSmith/EfCore.SoftDeleteServices#9]
Is it possible to use `SingleSoftDeleteServiceAsync<T>` in a `DbContext`? I want to override `dbContext.SaveChangesAsync()` and use this service for soft delete, but can't, beacuse `DbContext` should be registered first in DI.
Thanks in advance!

**Comment by JonPSmith** [comment]
Hi @ksydex,

> Is it possible to use `SingleSoftDeleteServiceAsync<T>` in a `DbContext`?

I would like to ask why you want to to put the soft delete server inside your DbContext? If you want to change a delete into a soft delete, then I recommend you don't do that. That's because a hard deletes (my term for a `Remove`) often causes cascade deletes of other dependant entities, and you won't be able to undelete that properly.

This soft delete library is designed to be a replacement for the `Remove` method, and the cascade soft delete version of this library will soft delete including cascade deletes in the same way that a hard delete would cascade deletes.

The other problem of calling a soft delete service inside `SaveChangesAsync` are:

- You need to use the soft delete services that have the `callSaveChanges` parameter so that you stop the method from called SaveChanges again.
- The other issue is you might need to call `ChangeTracker.DetectChanges();` after you have called the soft delete methods.

All in all I wouldn't go this way.

> I want to override dbContext.SaveChangesAsync() and use this service for soft delete, but can't, because DbContext should be registered first in DI.

Its not obvious, but you can inject services into your DbContext if you have registered your DbContext with DI, e.g. adding 
`services.AddDbContext<EfCoreContext>(options => options.UseSqlServer(connection));` in your startup code.

Once your DbContext is registered with the DI provider you can use DI constructor injection in your DbContext's constructor. For instance:

```c#
public class EfCoreContext: DbContext
{
    private SingleSoftDeleteServiceAsync<ISingleSoftDelete> _softDelService;

    public EfCoreContext(DbContextOptions<EfCoreContext> options,
         SingleSoftDeleteServiceAsync<ISingleSoftDelete> softDelService)
        : base(options) 
       {
               _softDelService = softDelService;
       }

      //... rest of DBContext left out
}
```

**Comment by ksydex** [comment]
@JonPSmith Got it! Thanks for the answer and explanation 👍
